- hosts: all
  become: true

  vars:
     app_dir: /var/www/webapp
     venv_path: "{{ app_dir }}/venv"
     nginx_group: www-data
     nginx_user: www-data
     vassal_dir: /etc/uwsgi/vassals
     uwsgi_log_dir: /var/log/uwsgi/
     uwsgi_service_name: uwsgi_emperor
     handler_function: serve
     python_file_base: index # no .py here
     database_name: web_data
     sql_user: root # TODO: change
     table_name: staff_info

  tasks:

     - name: add nginx apt repo
       apt_repository:
          repo: ppa:nginx/stable
       become: yes

     - name: install dependencies, update apt
       apt:
          name:
             - nginx
             - python3
             - python3-pip
             - mysql-server
             - tmux # convenience
             - vim  # convenience
             - build-essential # for WSGI (nginx-python)
          state: present
          update_cache: yes
       become: yes

     # TODO: create non-root user
     - name: create app directory
       file:
          path: "{{ item }}"
          state: directory
          owner: "{{ nginx_user }}"
          group: "{{ nginx_group }}"
          recurse: yes
       become: yes
       with_items:
          - "{{ app_dir }}"
          - "{{ app_dir }}/static"
       tags:
          - static_content
          - dynamic_content
          - content

     - name: copy static files over
       template:
          src: "static/{{ item }}"
          dest: "{{ app_dir }}/static/{{ item }}"
       with_items:
          - index.html
          - styles.css
          - script.js
       tags:
          - static_content
          - content

     - name: install virtualenv tool
       pip:
          name: virtualenv
          executable: pip3

     - name: create virtual env
       pip:
          name: 
            - flask
            - uwsgi
          virtualenv: "{{ venv_path }}"
          virtualenv_python: python3


     - name: copy python flask script over
       template:
          src: app.py
          dest: "{{ app_dir }}/{{ python_file_base }}.py"
       register: flask_script
       tags:
          - content
          - dynamic_content

     # nginx + flask guide: https://vladikk.com/2013/09/12/serving-flask-with-nginx-on-ubuntu/
     # (with tweaks to template into jinja, and convert to systemd)
     - name: disable default nginx page
       file:
          path: /etc/nginx/sites-enabled/default
          state: absent

     - name: create new nginx conf
       template:
          src: nginx.conf
          dest: /etc/nginx/sites-available/hello.conf
       register: nginx_conf

     - name: enable new nginx conf
       file: 
         src: "{{ nginx_conf.dest }}"
         dest: /etc/nginx/sites-enabled/hello.conf
         state: link

     - name: copy uwsgi conf
       template:
          src: app_uwsgi.ini
          dest: "{{ app_dir }}/app_uwsgi.ini"
       register: uwsgi_ini

     - name: create log dir for uwsgi
       file:
          path: /var/log/uwsgi
          state: directory
          owner: "{{ nginx_user }}"
          group: "{{ nginx_group }}"

     - name: make vassals dir
       file:
          path: "{{ vassal_dir }}"
          state: directory
       # TODO ownership of this dir?

     - name: create link so app is a vassal
       file:
          src: "{{ uwsgi_ini.dest }}"
          dest: "{{ vassal_dir }}/app_uwsgi.ini"
          state: link

     # this is for debugging
     # so you can manually invoke what systemd would invoke
     - name: copy manual emperor script
       template:
          src: run_emperor.sh
          dest: "{{ app_dir }}/run_emperor.sh"
          mode: "+x"

     - name: copy systemd service file
       template:
         src: emperor.service
         dest: /etc/systemd/system/{{ uwsgi_service_name }}.service

     - name: run systemd service for emperor and nginx
       systemd:
          name: "{{ item }}"
          state: restarted # TODO: only restart when really needed
          enabled: yes

       with_items:
          - "{{ uwsgi_service_name }}"
          - nginx
       tags:
          - content
          - dynamic_content

     - name: copy over mysql init script

       template:
         src: database_init.sql
         dest: /tmp/database_init.sql
       register: db_init_script
       tags:
          - db_init

     # there is an ansible module for this
     # but it seems to be unable to detect the required dependencies
     # even though they're definitely installed
     # TODO: password protect sql database
     - name: initialise mysql database
       shell: mysql -u {{ sql_user }} < {{ db_init_script.dest }}
       tags:
         - db_init
#     - name: initialise mysql database
#       mysql_db:
#         state: import
#         name: all
#         target: "{{ db_init_script.dest }}"
#       tags:
#         - db_init

